import { ColumnConfig } from "./types";

export const OPERATORS = ["=", ">", "<", "contains", "does not contain"];

export const COLUMN_CONFIG: ColumnConfig[] = [
  { id: "name", label: "Name", type: "string" },
  {
    id: "stage",
    label: "Stage",
    type: "tags",
    options: ["Prospect", "Lead", "Important", "Negotiation"],
  },
  { id: "niftyColumn", label: "My Nifty Column", type: "string" },
  { id: "lastInteraction", label: "Date of Last Interaction", type: "date" },
  { id: "patientsReferred", label: "Patients Referred", type: "number" },
  { id: "closeDate", label: "Close Date", type: "date" },
  { id: "dealSize", label: "Deal Size", type: "number" },
  { id: "coffeeShop", label: "Coffee Shop", type: "boolean" },
];

export const ROW_DATA = [
  {
    name: "Alice",
    stage: "Lead",
    niftyColumn: "Awesome",
    lastInteraction: "2024-01-05",
    patientsReferred: 5,
    closeDate: "2024-02-15",
    dealSize: 10000,
    coffeeShop: "True",
  },
  {
    name: "Bob",
    stage: "Prospect",
    niftyColumn: "Interesting",
    lastInteraction: "2024-01-03",
    patientsReferred: 10,
    closeDate: "2024-03-10",
    dealSize: 15000,
    coffeeShop: "False",
  },
  {
    name: "Charlie",
    stage: "Negotiation",
    niftyColumn: "Important",
    lastInteraction: "2024-01-10",
    patientsReferred: 2,
    closeDate: "2024-04-20",
    dealSize: 20000,
    coffeeShop: "True",
  },
  {
    name: "Diana",
    stage: "Lead",
    niftyColumn: "Interesting",
    lastInteraction: "2024-01-15",
    patientsReferred: 7,
    closeDate: "2024-03-15",
    dealSize: 12000,
    coffeeShop: "False",
  },
  {
    name: "Eve",
    stage: "Prospect",
    niftyColumn: "Awesome",
    lastInteraction: "2024-01-08",
    patientsReferred: 5,
    closeDate: "2024-02-20",
    dealSize: 13000,
    coffeeShop: "True",
  },
  {
    name: "Frank",
    stage: "Negotiation",
    niftyColumn: "Awesome",
    lastInteraction: "2024-01-12",
    patientsReferred: 3,
    closeDate: "2024-02-25",
    dealSize: 17000,
    coffeeShop: "False",
  },
  {
    name: "Grace",
    stage: "Prospect",
    niftyColumn: "Important",
    lastInteraction: "2024-01-18",
    patientsReferred: 10,
    closeDate: "2024-03-30",
    dealSize: 15000,
    coffeeShop: "True",
  },
  {
    name: "Hank",
    stage: "Lead",
    niftyColumn: "Important",
    lastInteraction: "2024-01-20",
    patientsReferred: 8,
    closeDate: "2024-03-05",
    dealSize: 20000,
    coffeeShop: "True",
  },
  {
    name: "Ivy",
    stage: "Negotiation",
    niftyColumn: "Awesome",
    lastInteraction: "2024-01-22",
    patientsReferred: 4,
    closeDate: "2024-03-25",
    dealSize: 16000,
    coffeeShop: "True",
  },
  {
    name: "Jack",
    stage: "Prospect",
    niftyColumn: "Interesting",
    lastInteraction: "2024-01-28",
    patientsReferred: 9,
    closeDate: "2024-03-10",
    dealSize: 14000,
    coffeeShop: "False",
  },
];
